# Generated by Django 4.2.6 on 2023-11-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_leads_property_intrested_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
