# Generated by Django 4.2.6 on 2023-11-10 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Businesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150)),
                ('asking_price', models.CharField(max_length=150)),
                ('business_name', models.CharField(max_length=150)),
                ('business_owner', models.CharField(max_length=150)),
                ('business_photo', models.ImageField(upload_to='')),
                ('cashflow', models.CharField(max_length=150)),
                ('gross_annual_revenue', models.CharField(max_length=150)),
                ('profits', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('county', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('realestate', models.CharField(choices=[('OD', 'owned'), ('LD', 'leased')], default='LD', max_length=2)),
                ('lease_expiration', models.DateField(blank=True, null=True)),
                ('inventory', models.TextField(blank=True, null=True)),
                ('number_of_employes', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('competion', models.TextField(blank=True, null=True)),
                ('support_and_training', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('closed_deal', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='businesses.categories')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='businesses.industry')),
            ],
        ),
    ]
