# Generated by Django 4.2.6 on 2023-11-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='name',
            field=models.CharField(default='twiter', max_length=100),
            preserve_default=False,
        ),
    ]
