# Generated by Django 4.2.6 on 2023-11-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_sociallink_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='are_you',
            field=models.CharField(choices=[('agent', 'agent'), ('owner', 'owner'), ('buyer', 'buyer')], max_length=7),
        ),
    ]
