# Generated by Django 4.2.6 on 2023-11-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_user_are_you'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='are_you',
            field=models.CharField(blank=True, choices=[('agent', 'agent'), ('owner', 'owner'), ('buyer', 'buyer')], max_length=7, null=True),
        ),
    ]
